### ISSUE TITLE
[BUG]: SK required fields not validated on .get

### ISSUE THREAD

**Issue by spearmootz** [sensedeep/dynamodb-onetable#98] opened 2021-08-16 20:31 UTC
**Describe the bug**
Entity.get does not require fields required by SK.

This may be a debatable bug or it could be seen as a feature.  Lets say i have an Entity on a table that uses PK and SK, the SK requires a field ID.  if i do Entity.get({ pk: 'somePk' }) i will get the first matching entity instead of requiring the ID of the entity i am looking for.  This behavior is completely acceptable in Entity.find, but i dont think its right for Entity.get.

At the very least there should be an option of the table such as strictGet that validates that the required parameters for the SK are provided

**Comment by mobsense** [comment] 2021-08-16 23:18
You are right, get should require the full primary key. We should be able to throw an exception if SK not provided. 

Validating for TypeScript would require an extra type. This may or may not be worthwhile as there are a few such cases and having a multitude of types leads to other problems. There is no free lunch.

**Comment by spearmootz** [comment] 2021-08-16 23:24
Yeah, i can imagine typescript validation must be hard. But i think run time validation would suffice as a feature.

**Comment by mobsense** [comment] 2021-08-17 01:59
I've committed a fix for this. If you do a `get` without a required sort key, the API will throw.

**Comment by mobsense** [comment] 2021-08-20 06:22
Fixed in 1.7.3

**Comment by spearmootz** [comment] 2021-08-20 06:27
Super! Thanks!!!

**Comment by mobsense** [comment] 2021-08-23 10:43
Unintended consequence.

Seems get was being used without an SK but with other fields to create a filter expression. This is actually pretty convenient when you know the PK + filter expression identifies only a single item.

With this change, users now need to do:

let item = (await Model.find({})[0]

The alternative is to revert to the prior behavior and check that only one item is found. If more than one is found, then error.

Thoughts?

**Comment by spearmootz** [comment] 2021-08-23 18:32
Hmmm I feel like throwing when more than one is found is definitely better than not doing anything.

I guess that is fine, i can't come up with a good argument against doing that and it doesn't seem terrible. 

The other option is to specify the desired behavior when defining the model. And it could be defaulted to false, and turned true if the property isn't provided.

But either might be fine.

**Comment by mobsense** [comment] 2021-08-23 23:46
Thanks -- we're going to revert this change in favor of:

* Get without a sort key will fall back to do a find() with filter expressions and if that returns 1 result -- all okay
* If the find returns > 1 result, an exception will be thrown.

**Comment by spearmootz** [comment] 2021-08-24 02:40
im pretty sure this is related, but i started getting and error saying sort key was missing.

"Missing sort key"

i was executing this code 

```return this.UserFileModel.get({ username, id });```

the sort key is this

```
sk: {
    type: String,
    value: '${_type}:${id}',
  },
  ```
  
  because SK is of a composed value, i would not expect us to have to manually set the SK

**Comment by mobsense** [comment] 2021-08-24 02:41
What version?  or is that with the `main` branch?

**Comment by mobsense** [comment] 2021-08-24 03:31
The issue is using {_type} in the template.  We are not setting _type in the properties.

The fix is below. 

```
@@ -722,6 +749,9 @@ export class Model {
     /* private */
     async getItem(properties, params = {}) {
         ({params, properties} = this.checkArgs(properties, params))
+        if (!this.generic) {
+            properties[this.typeField] = this.name
+        }
         properties = this.prepareProperties('get', properties, params)
         let expression = new Expression(this, 'get', properties, params)
         return await this.run('get', expression)
```

**Comment by mobsense** [comment] 2021-08-24 03:34
Re-opened due to _type not being handled.

**Comment by spearmootz** [comment] 2021-08-25 04:50
so will this be released? if so, i can let you know how it goes.  I am building things with unit tests so thats why i am catching these things

**Comment by mobsense** [comment] 2021-08-25 05:49
Yes, should be fixed for using _type.

**Closed by mobsense** 2021-08-25 05:49 UTC
Labels: bug

**Comment by spearmootz** [comment] 2021-08-25 16:26
so i updated to 1.7.4

relevant schema

  pk: { type: String, value: 'User:${username}' },
  username: {
    type: String,
    required: true,
    map: 'u',
    transform: (_model: any, _op: any, _name: any, username: string) =>
      username.toLowerCase(),
  },
 sk: {
    type: String,
    value: '${_type}:${id}',
  },
 id: {
    type: String,
    required: true,
  },

The error i get

   Missing sort key

      31 |
      32 |   delete(username: string, id: string) {
    > 33 |     return this.UserFileModel.remove({ username, id });
         |                               ^
      34 |   }
      35 | }


If i take off the _type from the SK it works well. but with _type or type the tests fail.
