### ISSUE TITLE
v2.6.0 error with  @aws-sdk/client-dynamodb v3

### ISSUE THREAD

**Issue by projaguar** [sensedeep/dynamodb-onetable#447] opened 2023-02-15 15:48 UTC
ERROR
-----------------------------------------------------------------------------------------------

Cannot find module 'aws-sdk/clients/dynamodb' from 'node_modules/dynamodb-onetable/dist/cjs/Table.js'

TEST CODE
-----------------------------------------------------------------------------------------------
import Dynamo from 'dynamodb-onetable/Dynamo';
import { Table } from 'dynamodb-onetable';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { UserSchema } from '@pnds/common-types';
describe('One Repository', () => {
  let client;
  let table;

  beforeEach(() => {
    process.env.AWS_ACCESS_KEY_ID = '------';
    process.env.AWS_SECRET_ACCESS_KEY = '-------';
    // process.env.AWS_REGION = 'ap-northeast-2';
    client = new Dynamo({
      client: new DynamoDBClient({
        endpoint: 'http://localhost:8000',
      }),
    });

    table = new Table({
      client,
      name: 'user',
      schema: UserSchema,
      partial: true,
    });
  });

  it('should be defined', () => {
    expect(client).toBeDefined();
  });
});

RESULT
-----------------------------------------------------------------------------------------------
❯ node 'node_modules/.bin/jest' '/Users/projaguar/projects/sorcerer/packages/libs-nestjs/dynamodb/src/dynamodb-onetable.spec.ts' -t 'One Repository should be defined'
watchman warning:  Recrawled this watch 45 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/projaguar/projects/sorcerer' ; watchman watch-project '/Users/projaguar/projects/sorcerer'`

 FAIL  packages/libs-nestjs/dynamodb/src/dynamodb-onetable.spec.ts
  ● Test suite failed to run

    Cannot find module 'aws-sdk/clients/dynamodb' from 'node_modules/dynamodb-onetable/dist/cjs/Table.js'

    Require stack:
      node_modules/dynamodb-onetable/dist/cjs/Table.js
      node_modules/dynamodb-onetable/dist/cjs/index.js
      packages/libs-nestjs/dynamodb/src/dynamodb-onetable.spec.ts

     ....

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.567 s, estimated 3 s
Ran all test suites matching /\/Users\/projaguar\/projects\/sorcerer\/packages\/libs-nestjs\/dynamodb\/src\/dynamodb-onetable.spec.ts/i with tests matching "One Repository should be defined".

-----------------------------------------------------------------------------------------------
If I use previous version, it's works well.

thanks for your effort

**Comment by mobsense** [comment] 2023-02-15 20:37
Duplicate of #446

**Comment by dev-embedthis** [comment] 2023-02-16 03:53
Fixed in 2.6.1

**Closed by dev-embedthis** 2023-02-16 03:53 UTC
Labels: bug, duplicate, fixed
