### ISSUE TITLE
batchget with parse: true returns empty array

### ISSUE THREAD

**Issue by ShivamJoker** [sensedeep/dynamodb-onetable#338] opened 2022-05-21 18:59 UTC
**Describe the bug**

Unmarshal doesn't work with `batchGet`, setting parse to true results in empty array.

**To Reproduce**

> Steps to reproduce the behavior:
> 
> 1. Clone this repository. Must test against the current master branch in the repository.
> 2. Edit your reproducible, MINIMAL, stand-alone test case into the test/debug.ts file.
> 3. Run via `jest debug` or run VS code in the top level directory.
> 
> If you don't provide a complete debug.ts that demonstrates your issue, then your issue will not receive priority.

**Sorry! Feels like a lot of work to do to just report an issue**

Schema

```js 
const Schema = {
  format: "onetable:1.1.0",
  version: "1.0.0",
  indexes: {
    primary: { hash: "PK", sort: "SK" },
    gs1: { hash: "GSI1PK", sort: "GSI1SK" },
  },
  models: {
    Song: {
      PK: { type: String, value: "USER#${username}" },
      SK: { type: String, value: "SONG#${id}" },
      GSI1PK: { type: String, value: "SONG" },
      GSI1SK: { type: String, value: "SONG#{id}" },
      username: { type: String, required: true },
      genre: { type: String, enum: Object.values(Genre) },
      id: { type: String, required: true },
      albums: {
        type: Array,
        default: [],
      },
    },
    Album: {
      PK: { type: String, value: "USER#${username}" },
      SK: { type: String, value: "ALBUM#${id}" },
      GSI1PK: { type: String, value: "ALBUM" },
      GSI1SK: { type: String, value: "ALBUM#{id}" },
      username: { type: String, required: true },
      genre: { type: String },
      id: { type: String, required: true },
      songs: {
        type: Array,
        default: [],
      },
    },
  },
```

How I am fetching

```js
  const batch = {};

  for (const album of albums) {
    await Album.get({ id: album.id, username: userId }, { batch});
  }

  const albumsRes = await SongTable.batchGet(batch);

  console.log(JSON.stringify(albumsRes, null, 4));
```

What do I get in response

```json
        "songs": {
            "L": [
                {
                    "M": {
                        "title": {
                            "S": "there there"
                        },
                        "id": {
                            "S": "1234"
                        }
                    }
                }
            ]
        },
```

**Expected behavior**
It should return the parsed object like

```js
{
  GSI2PK: 'LIKE_COUNT',
  songs: [ { title: 'there there', id: '1234' } ],
  GSI1PK: 'ALBUM',
  release_date: '2022-05-21',
  SK: 'ALBUM#01G3JZ01ABV6BF1WRJQH1VVP90',
  GSI1SK: 'ALBUM#01G3JZ01ABV6BF1WRJQH1VVP90',
  PK: 'USER#4114fcd0-9659-4ee8-9395-a35a79cdcdfd',
  album_art: 'ziki-images/defaultCover.png',
  GSI2SK: 0,
  title: 'Test Album'
}
```

**Environment (please complete the following information):**
 - OS - manjaro linux
 - Node Version - v16.14.2
 - OneTable Version - ^2.3.6
 - TypeScript Version - ^4.6.4

**Comment by ShivamJoker** [comment] 2022-05-24 15:45
> pass `parse: true` on options for batchGet method

Did you even read my issue properly?

**Comment by onhate** [comment] 2022-05-24 15:57
well, the main issue here is parse: true returning empty array, and not calling batchGet without parse not parsing, that is the expected behavior, rename the issue so people will be aware of the real issue "batchget with parse: true returns empty array"

**Comment by onhate** [comment] 2022-05-24 15:58
I'll try to debug here and find why it would happen

**Comment by ShivamJoker** [comment] 2022-05-24 16:06
I'll rename the issue, but you should not blame someone else because you didn't read the first two lines of the issue.

**Comment by mobsense** [comment] 2022-06-18 02:52
Works here in our batch unit test. BatchGet with parse: true is working.

The reason we ask for a test case is exactly for this situation where it works for us, but not for you.

I'll close this issue, but please feel free to reopen with debug.ts that demonstrates the issue.

**Closed by mobsense** 2022-06-18 02:52 UTC
Labels: Insufficient Information

**Comment by ShivamJoker** [comment] 2022-06-18 04:22
@mobsense aren't you guys mocking DynamoDB in the unit test? Is it testing against a real database?

**Comment by mobsense** [comment] 2022-06-18 08:11
Yes and yes.

**Comment by Matheuss1** [comment] 2024-05-16 22:52
I don't if this is was your case, but I was having a similar problem and the reason for {parse: true} to return an empty array was that I had some entries on database (entries that I was trying to get) without the field "_type".

I had created this entries manually. Maybe your records are just inconsistent for the library?
