### ISSUE TITLE
[TypeScript] bug: required modal properties typed as undefined

### ISSUE THREAD

**Issue by rdelcampog** [sensedeep/dynamodb-onetable#185] opened 2021-11-10 09:10 UTC
**Describe the bug**
Required modal properties are always typed as "\<type> | undefined" instead of just "\<type>".

**To Reproduce**

Define a model like:

```
export const Cart = {
  pk: { type: String, value: '${_type}#${cartId}' },
  sk: { type: String, value: '${_type}#${cartId}' },

  cartId: { type: String, uuid: true, validate: /^[0-9A-Z]{26}$/i, required: true },
  total: { type: String },
};

export type CartType = Entity<typeof Cart>;

const cart: CartType = {
  cartId: '01FM4EY71FQSD8XK5TPWX722WJ', <---------- This is typed as "string | undefined"
  total: '100,00€',
};
```

I'm not a TypeScript expert so I can't help doing a PR but changing "extends true" to "extends boolean" makes "cartId" field only of type "string" not "string | undefined" so I assume that the required field type must be checked as boolean and then as true:

```
export type Entity<T extends OneTypedModel> = UndefinedToOptional<{
  [P in keyof T]: T[P]['required'] extends true ? EntityField<T[P]> : EntityField<T[P]> | undefined;
}>;
```

**Screenshots**
![imagen](https://user-images.githubusercontent.com/4947468/141083756-921fb19b-0a34-4aad-9372-8dac60d25af2.png)
![imagen](https://user-images.githubusercontent.com/4947468/141083891-cd96c10e-2319-4a3c-bcd7-0acd75159ffe.png)

**Environment (please complete the following information):**
 - *OS:* Mac OS 11.5.2
 - *Node Version:* v14.18
 - *OneTable Version:* v2.1.0 (latest)

**Comment by estyh** [comment] 2021-11-10 09:46
Just came across the same issue

**Comment by mobsense** [comment] 2021-11-10 21:06
Thanks for raising. @spearmootz  do you have insights into this? Originally in issue #126

**Comment by spearmootz** [comment] 2021-11-10 21:55
Changing it to boolean i think will not work because it will make not required things to be only the string instead of string | undefined

Now, I'm certain that when i did this it worked just fine as i tested it in my codebase.

What is the typescript version?

**Comment by mobsense** [comment] 2021-11-10 21:56
From my testing, it looks like the use of 'undefined' as the marker is breaking it. Must be a TS upgrade.

I'm prototyping with using a

type UndefinedMarker = {}

instead of undefined and I think it works again.  More results soon.

**Comment by mobsense** [comment] 2021-11-10 22:04
If I use a different type than 'undefined', like UndefinedMarker = {}, then it works. However, the types look messed up with introspection as the UndefinedMarker is not erased.

```

type UndefinedMarker = {}

type UndefinedProperties<T> = {
    [P in keyof T]-?: UndefinedMarker extends T[P] ? P : never
}[keyof T]

export type UndefinedToOptional<T> = Partial<Pick<T, UndefinedProperties<T>>> & Pick<T, Exclude<keyof T, UndefinedProperties<T>>>

export type Entity<T extends OneTypedModel> = UndefinedToOptional<{
    [P in keyof T]: T[P]['required'] extends true ? EntityField<T[P]> : (UndefinedMarker | EntityField<T[P]>)
}>
```

![image](https://user-images.githubusercontent.com/168091/141201037-3ef3d436-ee1f-45ee-8627-86060488c9c7.png)

```

**Comment by mobsense** [comment] 2021-11-10 22:08
I'm testing with TSC 4.3.2 which has this problem.

**Comment by mobsense** [comment] 2021-11-10 22:09
One question too:

    [P in keyof T]-?: undefined extends T[P] ? P : never

Is the undefined extends back to front.  Should it not be T[P] extends undefined?

**Comment by mobsense** [comment] 2021-11-10 22:17
So testing with UndefinedMarker validates that the previous use of undefined is the issue. However, using another type like UndefinedMarker pollutes the field types.

@spearmootz I need your help on this one. I'm not quite the TS expert!

**Comment by spearmootz** [comment] 2021-11-10 22:23
@mobsense i am not either, but I'll take a look tomorrow before noon

**Comment by shawnmclean** [comment] 2021-11-24 01:27
Is there a solution to this? I'm hitting this behavior in tsc 4.4.4.

```
export const AccountsSchema: OneSchema = {
  models: {
    Organization: {
      pk: { type: String, value: '${_type}#${id}' },
      sk: { type: String, value: '${_type}#${id}' },
      id: { type: String, required: true, uuid: 'ulid', validate: /^[0-9A-F]{32}$/i },
      name: { type: String, required: true },
    },
  }
};

export type OrganizationType = Entity<typeof AccountsSchema.models.Organization>;
```

```
    const org: OrganizationType = {
      id: orgId, <-- Type 'string' is not assignable to type 'undefined'.
      name: `${name}'s Org`, <--  Type 'string' is not assignable to type 'undefined'.
    };
```

**Comment by mobsense** [comment] 2021-11-24 03:58
I'm not sure that is the same issue. I tried to reproduce your code fragments and it worked for me when edited into debug.ts as per issue template:

Can you please raise a new issue with full description, where the error is coming from (unclear in your description) and edited into debug.ts so we can reproduce.

```const Schema = {
    version: '0.0.1',
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
        gs1: { hash: 'gs1pk', sort: 'gs1sk', project: 'all' },
    },
    models: {
        Organization: {
            pk: { type: String, value: '${_type}#${id}' },
            sk: { type: String, value: '${_type}#${id}' },
            id: { type: String, required: true, uuid: 'ulid', validate: /^[0-9A-F]{32}$/i },
            name: { type: String, required: true },
        }
    }
}

type OrganizationType = Entity<typeof Schema.models.Organization>;

let orgId = '1234'
let name = 'Peter'
const org: OrganizationType = {
    id: orgId,                //  <-- Type 'string' is not assignable to type 'undefined'.
    name: `${name}'s Org`,    //  <--  Type 'string' is not assignable to type 'undefined'.
};

```

**Comment by mobsense** [comment] 2021-11-24 06:42
We're making progress on supporting TS required properties. Should not be long to get required props fully supported.

Cleaning up the TS definitions to be more supportable too.

**Comment by mobsense** [comment] 2021-11-24 09:00
Got It!!!!!

Pretty readable too.  

Now onto nested schemas (recursive types) Ugh!

```
/*
    Select the required properties from a model
*/
export type Required<T extends OneTypedModel> = {
    -readonly [P in keyof T as T[P]['required'] extends true ? P : never]: EntityField<T[P]>
};

/*
    Select the optional properties from a model
*/
export type Optional<T extends OneTypedModel> = {
    -readonly [P in keyof T as T[P]['required'] extends true ? never : P]?: EntityField<T[P]>
};

/*
    Merge two types
*/
type Merge<A, B> = { 
    [P in keyof (A & B)]: P extends keyof A ? A[P] : B[P]
};

/*
    Create entity type which includes required and optional types
*/
type Entity<T extends OneTypedModel> = Merge<Required<T>, Optional<T>>
```

**Comment by mobsense** [comment] 2021-11-24 22:38
Fixed in 2.1.2

**Comment by shawnmclean** [comment] 2021-11-25 03:11
@mobsense 2.1.2 fixed the typescript assignment error but now I'm getting another set of errors:

Just going to throw it here and revert to 2.1.1 and do `id: id as unknown as undefined` on the properties as a workaround for now.
```
Encountered 3 errors:
  [typescript] ../../common/temp/node_modules/.pnpm/dynamodb-onetable@2.1.2/node_modules/dynamodb-onetable/dist/mjs/index.d.ts:11:5 - (TS2305) Module '"./Model"' has no exported member 'OneFieldSchema'.
  [typescript] ../../common/temp/node_modules/.pnpm/dynamodb-onetable@2.1.2/node_modules/dynamodb-onetable/dist/mjs/Model.d.ts:37:20 - (TS2304) Cannot find name 'OneFieldSchema'.
  [typescript] ../../common/temp/node_modules/.pnpm/dynamodb-onetable@2.1.2/node_modules/dynamodb-onetable/dist/mjs/Model.d.ts:122:54 - (TS2536) Type 'P' cannot be used to index type 'B'.

```

**Comment by mobsense** [comment] 2021-11-25 03:23
Ugh!  Sorry. Will update immediately.

One more thing that is required with the 2.1.2+.

You must put "as const" after your model declarations. E.g.

```
    models: {
        User: {
            pk:         { type: String, value: 'Account#${accountId}' },
            sk:         { type: String, value: '${_type}#${id}' },
            id:         { type: String, uuid: true },
            name:       { type: String, required: true },
            email:      { type: String, required: true },
        },
    } as const

```

**Comment by mobsense** [comment] 2021-11-25 04:22
Sorry @shawnmclean that should be fixed now.

**Closed** 2021-11-25 09:01 UTC
Labels: bug
